---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-12.04
  - name: ubuntu-14.04

suites:
- name: default
  run_list:
    - recipe[apt]
    - recipe[unifi]
  attributes:
    apt:
      compile_time_update: true
