driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: debian-7.10
  - name: debian-8.4
  - name: ubuntu-12.04
  - name: ubuntu-14.04
  - name: ubuntu-16.04

suites:
- name: default
  run_list:
    - recipe[apt]
    - recipe[unifi]
